# permissions for end users to edit iflearnerjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: iflearnerjob-editor-role
rules:
- apiGroups:
  - git.iflytek.com
  resources:
  - iflearnerjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - git.iflytek.com
  resources:
  - iflearnerjobs/status
  verbs:
  - get
