---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - git.iflytek.com
  resources:
  - iflearnerjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - git.iflytek.com
  resources:
  - iflearnerjobs/finalizers
  verbs:
  - update
- apiGroups:
  - git.iflytek.com
  resources:
  - iflearnerjobs/status
  verbs:
  - get
  - patch
  - update
