apiVersion: git.iflytek.com/v1
kind: IflearnerJob
metadata:
  name: iflearnerjob-client1
spec:
  role: client
  host: job1.a.party.iflearner.com
  template:
    spec:
      restartPolicy: Never
      containers:
      - image: iflearner:0.1.3   
        name: iflearnerjob-client
        imagePullPolicy: IfNotPresent
        workingDir: /iflearner/examples/homo/quickstart_pytorch
        args:
        - sleep
        - 1d

        # - python
        # - -u
        # - quickstart_pytorch.py   
        # - --name=test
        # - --epochs=10
        # - --server=s1.server.iflearner.com:30031
        # - --cert=/etc/server-iflearner-secret.crt
