apiVersion: git.iflytek.com/v1
kind: IflearnerJob
metadata:
  name: iflearnerjob-server
spec:
  role: server
  host: job1.server.iflearner.com
  template:
    spec:
      containers:
      - image: ghcr.io/iflytek/iflearner:v0.1.0
        name: iflearnerjob-server
        imagePullPolicy: IfNotPresent
        args:
        - python 
        - iflearner/business/homo/aggregate_server.py 
        - -n=2
        - --epochs=10
